[build]
base = "netlify"
publish = "public"
command = """\
NODE_PATH=node_modules node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml && \
node_modules/.bin/antora --html-url-extension-style=indexify --redirect-facility=netlify ../antora-playbook.yml\
"""

[build.environment]
NODE_VERSION = "10"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
command = """\
NODE_PATH=node_modules node_modules/.bin/antora --fetch --generator=@antora/xref-validator ../antora-playbook.yml && \
node_modules/.bin/antora --url $DEPLOY_PRIME_URL --html-url-extension-style=indexify --redirect-facility=netlify ../antora-playbook.yml\
"""

[[redirects]]
from = "/"
to = "/hercules-ci/"
status = 302
